---
name: "Session Cleaner"
guid: "EC9E2A74-1311-4A14-B302-158E3D95FD1D"
version: "2.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "crobibero"
overview: "Removes old sessions (devices)."
description: >
  Removes old sessions (devices).
category: "General"
artifacts:
- "Jellyfin.Plugin.SessionCleaner.dll"
changelog: >
  10.8 support
