---
name: "Session Cleaner"
guid: "EC9E2A74-1311-4A14-B302-158E3D95FD1D"
version: 4
targetAbi: "10.9.9.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Removes old sessions (devices)."
description: >
  Removes old sessions (devices).

category: "General"
artifacts:
  - "Jellyfin.Plugin.SessionCleaner.dll"
changelog: |-
  - Fixes for Jellyfin 10.9.9 (#21) @crobibero
