---
name: "Session Cleaner"
guid: "EC9E2A74-1311-4A14-B302-158E3D95FD1D"
version: 5
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Removes old sessions (devices)."
description: >
  Removes old sessions (devices).

category: "Administration"
artifacts:
  - "Jellyfin.Plugin.SessionCleaner.dll"
changelog: |-
  - Jellyfin 10.11 support (#25) @crobibero
